### ISSUE TITLE
Odd pattern_error for "N24N"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/allele_qc#101]
Hi @manulera

I tried this in the allele_qc API:

```
systematic_id: SPBC359.03c
allele_description: N204N
allele_type: amino_acid_mutation
```

request:
```sh
curl -X 'GET' \
  'http://localhost:8808/check_allele?systematic_id=SPBC359.03c&allele_description=A204N&allele_type=amino_acid_mutation&allele_name=aat1-blah' \
  -H 'accept: application/json'
```

and got an odd result for "pattern_error": "N2,4N"

Here's the JSON response:

```json
{
  "allele_parts": "",
  "needs_fixing": true,
  "change_description_to": "",
  "rules_applied": "",
  "pattern_error": "N2,4N",
  "invalid_error": "",
  "sequence_error": "",
  "change_type_to": "",
  "user_friendly_fields": {
    "allele_parts": "",
    "needs_fixing": true,
    "change_description_to": "",
    "rules_applied": "",
    "pattern_error": "The following parts of the allele description do not follow the existing syntax: N2,4N",
    "invalid_error": "",
    "sequence_error": "",
    "change_type_to": "",
    "user_friendly_fields": null
  }
}
```

This that a bug?

If I change the description to "N204A" there's no problem.

And if I change the description to "A204N" the error makes sense:

```json
{
  "allele_parts": "A204N",
  "needs_fixing": true,
  "change_description_to": "",
  "rules_applied": "amino_acid_mutation:single_aa",
  "pattern_error": "",
  "invalid_error": "",
  "sequence_error": "A204",
  "change_type_to": "",
  "user_friendly_fields": {
    "allele_parts": "We identified 1 parts in the allele description, which are: A204N",
    "needs_fixing": true,
    "change_description_to": "",
    "rules_applied": "We identified that the allele parts correspond to the following types of mutations: amino_acid_mutation",
    "pattern_error": "",
    "invalid_error": "",
    "sequence_error": "The following sequence positions don't contain the indicated residues: A204",
    "change_type_to": "",
    "user_friendly_fields": null
  }
}
```

**Comment by manulera** [comment]
Hi @kimrutherford. This is the syntax rule for single amino acid substitutions. The reason why it fails is because of the function `further_check` which is run in the capture groups of the regex, that checks that the aminoacids before and after the number are different. I think it's ok to report this as not fitting any pattern, since it's not really describing a variant. We could remove it though

https://github.com/pombase/allele_qc/blob/4073d2c92e910cc80618a6dc0b0c282280a9d3ce/grammar.py#L310-L318

**Comment by manulera** [comment]
The reason why the pattern error is `N2,4N` is because it attempts to replace elements in the descriptions by the regex from the syntax rules in the grammar, starting by the one that matches the most characters. In this case, the only thing that fits a regex rule is the `0` character (single numbers could be representing the deletion of a single aminoacid). `N2` and `4N` are the substrings that are not matched by any regex, which are displayed as comma-separated values. A bit cryptic, admitedly!

**Comment by manulera** [comment]
Should we close this?

**Comment by kimrutherford** [comment]
Is there a way we can make the messages clearer when this sort of typo happens?

As an example for rad3, the description "S1901A,S1945S,A1976A,T2045A" gives this:

![image](https://github.com/pombase/allele_qc/assets/90474/f6377884-e686-443b-892b-95c3a7dc62cd)

(The description should be "S1901A,S1945A,S1976A,T2045A")

**Comment by manulera** [comment]
Hi @kimrutherford, the problem was that the pattern to detect single nucleotide / amino acid deletions (a single number) would match a number that is not preceded / followed by nucleotide / amino acid. I have added negative lookaheads and lookbehinds for digits as well in this [commit](https://github.com/pombase/allele_qc/pull/105/commits/6cbeac7102ea2e87a56f617cf2dd79c102cc416f#diff-7a5d4c6d2758d21ea01043fc46902c837f66b4ad02eca37799048ecc71a20aed). The error then becomes: "The following parts of the allele description do not follow the existing syntax: ,S1945S,A1976A,".

This is not yet merged into master, but will soon.

**Comment by manulera** [comment]
The changes are in with #105

**Comment by manulera** [comment]
I will close this one since the cases you mentioned are now not giving weird errors. If something else comes up you can re-open or make a new one.

**Comment by kimrutherford** [comment]
> The error then becomes: "The following parts of the allele description do not follow the existing syntax: ,S1945S,A1976A,".

Thanks Manu.  That's much better.
