### ISSUE TITLE
Same description, different names

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#51]
@kimrutherford @ValWood

There are also some cases where the same allele has different names in two sessions and it's not a mistake/typo, they seem to be genuinely differently named alleles from two publications. Examples from `log.2023-04-30-22-14-22.chado_checks.duplicate_allele_descriptions`

```
gtb1-P301L	729f627c0beaa1b2	P302L	gtb1-93
SPBC146.13c	myo1-delta23A	1c9a3835487bb72e	967-1217	myo1-H/1	f9a2c4769a3f8ab9
```

What should we do in these cases? Manually annotate them as synonyms? I don't think this should be done automatically, because these cases are often mistakes.

**Comment by ValWood** [comment]
OK it seems this is a new difference crept in because  myo1-delta23A has been added more reecently with a differnet name. 

These land in this file, and I fix manually (decide primary name and make alternative name synonym)

https://curation.pombase.org/dumps/latest_build/logs/log.2023-05-11-22-15-32.chado_checks.duplicate_allele_descriptions

I just wanted to check that  these were not generated by issues with the  new pipeline.

I think it is better to fix manually, and going forwards there should not be so many of these.
I will fix these two.

**Comment by ValWood** [comment]
I think I know what has happened........These have probably cropped up because we merged the expression types , these would have been treated as different allele types previously.

I was assuming that they were either recent curation, or pipeline since I didn't recognise them.

All good, I will adress them.
